### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by tilaprimera** [jjkester/django-auditlog#45] opened 2015-11-22 07:34 UTC
Installed django-auditlog, and kept auditlog in the settings.py and also the 'auditlog.middleware.AuditlogMiddleware', in the MIDDLEWARE Classes, but when I run,

    pip install django-auditlog

    MIDDLEWARE_CLASSES = (
      'auditlog.middleware.AuditlogMiddleware', ) 

in the settings.py file. 

Now, on running the server, 

    ./manage.py runserver,  

I get the following, 

    Operations to perform:
    Synchronize unmigrated apps: staticfiles, messages, widget_tweaks, inventory, crispy_forms, 
    bootstrap3
    Apply all migrations: admin, contenttypes, auditlog, auth, sessions
    Synchronizing apps without migrations:
    Creating tables...
    Running deferred SQL...
    Installing custom SQL... 
    Running migrations:
    Rendering model states... DONE
    Applying auditlog.0006_object_pk_index...Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/core/management/__init__.py", 
    line 338, in execute_from_command_line
    utility.execute()
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/core/management/__init__.py", 
    line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/core/management/base.py",
    line 
    393, in run_from_argv
    self.execute(*args, **cmd_options)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/core/management/base.py", 
     line 
    444, in execute
    output = self.handle(*args, **options)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site 
    -packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/migrations/executor.py", line
    110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/migrations/executor.py", line 
    148, in apply_migration
    state = migration.apply(state, schema_editor)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/migrations/migration.py", line
    115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site
    -packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/backends/base/schema.py",
    line 484, in alter_field
    old_db_params, new_db_params, strict)
     File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/backends/base/schema.py",
    line 670, in _alter_field
    self.execute(self._create_index_sql(model, [new_field], suffix="_uniq"))
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/backends/base/schema.py", 
    line 111, in execute
    cursor.execute(sql, params)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/backends/utils.py", line 79,  
    in
     execute
    return super(CursorDebugWrapper, self).execute(sql, params)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, 
    in 
    execute
    return self.cursor.execute(sql, params)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/backends/utils.py", line 64,
     in
     execute
    return self.cursor.execute(sql, params)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/django/db/backends/mysql/base.py", 
    line 124, in execute
    return self.cursor.execute(query, args)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in
    execute
    self.errorhandler(self, exc, value)
    File "/home/tilaprimera/Envs/tp/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in
    defaulterrorhandler
    raise errorclass, errorvalue
    django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'object_pk' used in key specification
    without a key length")

**Comment by jjkester** [comment] 2015-11-22 12:23
This seems to be an issue with MySQL specifically. However, I will investigate this.

The issue seems to be introduced with the addition of an index on a database column. Version 0.3.1 does not have this index, so you can try using that version for now.

**Comment by jjkester** [comment] 2016-01-23 20:48
As it turns out MySQL cannot index a TEXT type column. Also, MySQL does not support length-limiting a TEXT column. Therefore this field needs to be changed into a VARCHAR(255) field for MySQL.

This issue could be reproduced using Django 1.9.1, mysqlclient 1.3.7 and django-auditlog 0.3.2. However, the `object_pk` field did not have the index that django-auditlog 0.3.2 tried to add.

A fix is proposed in #49.

**Comment by jjkester** [comment] 2016-01-23 21:46
Closing this issue since a fix is about to be released. Please allow some time for the 0.3.3 release to be uploaded.

**Closed by jjkester** 2016-01-23 21:46 UTC
Labels: bug
